// instruments.js

export const instrumentsData = {
    "instruments": [
        {
            "name": "Guitar",
            "type": "String",
            "price_range": "$100 - $5000",
            "avg_rent_cost": "$20 - $100/month",
            "weight": "1 - 5 kg",
            "size": "Medium",
            "hands": 2,
            "groups": ["Rock Band", "Acoustic Ensemble"],
            "genres": ["Rock", "Pop", "Blues"]
        },
        {
            "name": "Clarinet",
            "type": "Woodwind",
            "price_range": "$200 - $3000",
            "avg_rent_cost": "$30 - $70/month",
            "weight": "1 - 2 kg",
            "size": "Medium",
            "hands": 2,
            "groups": ["Concert Band", "Jazz Ensemble"],
            "genres": ["Classical", "Jazz", "Swing"]
        },
        {
            "name": "Steel Drum",
            "type": "Percussion",
            "price_range": "$100 - $2000",
            "avg_rent_cost": "$30 - $80/month",
            "weight": "5 - 10 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Steel Band"],
            "genres": ["Calypso", "Reggae"]
        },
        {
            "name": "Piano",
            "type": "Keyboard",
            "price_range": "$500 - $50000",
            "avg_rent_cost": "$50 - $200/month",
            "weight": "200 - 500 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Solo", "Ensemble"],
            "genres": ["Classical", "Jazz", "Pop"]
        },
        {
            "name": "Oboe",
            "type": "Woodwind",
            "price_range": "$500 - $8000",
            "avg_rent_cost": "$40 - $100/month",
            "weight": "1 - 2 kg",
            "size": "Medium",
            "hands": 2,
            "groups": ["Orchestra", "Wind Ensemble"],
            "genres": ["Classical", "Film Score"]
        },
        {
            "name": "Recorder",
            "type": "Woodwind",
            "price_range": "$20 - $200",
            "avg_rent_cost": "$10 - $30/month",
            "weight": "0.1 - 0.3 kg",
            "size": "Small",
            "hands": 2,
            "groups": ["Early Music Ensemble", "School Bands"],
            "genres": ["Classical", "Folk"]
        },
        {
            "name": "Piccolo",
            "type": "Woodwind",
            "price_range": "$200 - $3000",
            "avg_rent_cost": "$30 - $70/month",
            "weight": "0.3 - 0.5 kg",
            "size": "Small",
            "hands": 2,
            "groups": ["Concert Band", "Marching Band"],
            "genres": ["Classical", "Marching Music"]
        },
        {
            "name": "Ukulele",
            "type": "String",
            "price_range": "$50 - $500",
            "avg_rent_cost": "$10 - $30/month",
            "weight": "0.5 - 1 kg",
            "size": "Small",
            "hands": 1,
            "groups": ["Solo", "Folk Bands"],
            "genres": ["Folk", "Pop", "Hawaiian"]
        },
        {
            "name": "Cello",
            "type": "String",
            "price_range": "$500 - $10000",
            "avg_rent_cost": "$50 - $150/month",
            "weight": "4 - 6 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Orchestra", "String Quartet"],
            "genres": ["Classical", "Folk", "Jazz"]
        },
        {
            "name": "Drum Set",
            "type": "Percussion",
            "price_range": "$500 - $5000",
            "avg_rent_cost": "$50 - $100/month",
            "weight": "20 - 30 kg",
            "size": "Large",
            "hands": 4,
            "groups": ["Rock Band", "Jazz Ensemble"],
            "genres": ["Rock", "Pop", "Metal"]
        },
        {
            "name": "Banjo",
            "type": "String",
            "price_range": "$200 - $2000",
            "avg_rent_cost": "$30 - $60/month",
            "weight": "2 - 5 kg",
            "size": "Medium",
            "hands": 1,
            "groups": ["Bluegrass Band", "Folk Ensemble"],
            "genres": ["Bluegrass", "Folk", "Country"]
        },
        {
            "name": "Organ",
            "type": "Keyboard",
            "price_range": "$1000 - $20000",
            "avg_rent_cost": "$100 - $300/month",
            "weight": "50 - 200 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Church Choir", "Rock Band"],
            "genres": ["Classical", "Gospel", "Rock"]
        },
        {
            "name": "Bassoon",
            "type": "Woodwind",
            "price_range": "$1000 - $8000",
            "avg_rent_cost": "$80 - $150/month",
            "weight": "2 - 3 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Orchestra", "Wind Ensemble"],
            "genres": ["Classical", "Film Score"]
        },
        {
            "name": "Harmonica",
            "type": "Wind",
            "price_range": "$10 - $100",
            "avg_rent_cost": "$5 - $20/month",
            "weight": "0.1 - 0.2 kg",
            "size": "Small",
            "hands": 1,
            "groups": ["Various"],
            "genres": ["Blues", "Folk", "Rock"]
        },
        {
            "name": "Bass",
            "type": "String",
            "price_range": "$300 - $5000",
            "avg_rent_cost": "$30 - $100/month",
            "weight": "3 - 6 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Rock Band", "Jazz Ensemble", "Orchestra"],
            "genres": ["Rock", "Jazz", "Funk"]
        },
        {
            "name": "Viola",
            "type": "String",
            "price_range": "$500 - $7000",
            "avg_rent_cost": "$40 - $120/month",
            "weight": "1 - 2 kg",
            "size": "Medium",
            "hands": 2,
            "groups": ["Orchestra", "String Quartet"],
            "genres": ["Classical", "Folk", "Jazz"]
        },
        {
            "name": "Bass Clarinet",
            "type": "Woodwind",
            "price_range": "$1000 - $8000",
            "avg_rent_cost": "$80 - $150/month",
            "weight": "2 - 3 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Concert Band", "Orchestra"],
            "genres": ["Classical", "Jazz"]
        },
        {
            "name": "Saxophone",
            "type": "Woodwind",
            "price_range": "$300 - $5000",
            "avg_rent_cost": "$30 - $100/month",
            "weight": "1 - 3 kg",
            "size": "Medium",
            "hands": 1,
            "groups": ["Jazz Band", "Marching Band"],
            "genres": ["Jazz", "Pop", "Rock"]
        },
        {
            "name": "Tin Whistle",
            "type": "Wind",
            "price_range": "$10 - $100",
            "avg_rent_cost": "$5 - $20/month",
            "weight": "0.1 - 0.2 kg",
            "size": "Small",
            "hands": 1,
            "groups": ["Folk Bands", "Traditional Irish Bands"],
            "genres": ["Folk", "Traditional"]
        },
        {
            "name": "Trumpet",
            "type": "Brass",
            "price_range": "$200 - $2000",
            "avg_rent_cost": "$30 - $60/month",
            "weight": "1 - 2 kg",
            "size": "Medium",
            "hands": 1,
            "groups": ["Marching Band", "Jazz Band", "Orchestra"],
            "genres": ["Jazz", "Funk", "Classical"]
        },
        {
            "name": "Trombone",
            "type": "Brass",
            "price_range": "$300 - $3000",
            "avg_rent_cost": "$40 - $80/month",
            "weight": "2 - 3 kg",
            "size": "Large",
            "hands": 1,
            "groups": ["Concert Band", "Jazz Band", "Orchestra"],
            "genres": ["Jazz", "Blues", "Classical"]
        },
        {
            "name": "Violin",
            "type": "String",
            "price_range": "$300 - $5000",
            "avg_rent_cost": "$40 - $80/month",
            "weight": "0.3 - 0.5 kg",
            "size": "Small",
            "hands": 2,
            "groups": ["Orchestra", "String Quartet"],
            "genres": ["Classical", "Folk", "Jazz"]
        },
        {
            "name": "Mandolin",
            "type": "String",
            "price_range": "$100 - $2000",
            "avg_rent_cost": "$20 - $50/month",
            "weight": "0.5 - 1 kg",
            "size": "Small",
            "hands": 1,
            "groups": ["Folk Bands", "Bluegrass Bands"],
            "genres": ["Folk", "Bluegrass", "Country"]
        },
        {
            "name": "Marimba",
            "type": "Percussion",
            "price_range": "$500 - $5000",
            "avg_rent_cost": "$50 - $100/month",
            "weight": "20 - 40 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Percussion Ensemble", "Orchestra"],
            "genres": ["Classical", "Contemporary"]
        },
        {
            "name": "French Horn",
            "type": "Brass",
            "price_range": "$500 - $8000",
            "avg_rent_cost": "$60 - $120/month",
            "weight": "3 - 4 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Orchestra", "Wind Ensemble"],
            "genres": ["Classical", "Film Score"]
        },
        {
            "name": "Accordion",
            "type": "Keyboard",
            "price_range": "$500 - $5000",
            "avg_rent_cost": "$50 - $150/month",
            "weight": "5 - 15 kg",
            "size": "Medium",
            "hands": 2,
            "groups": ["Folk Bands", "Polka Bands", "Tango Groups"],
            "genres": ["Folk", "Polka", "Tango"]
        },
        {
            "name": "Bagpipes",
            "type": "Wind",
            "price_range": "$500 - $3000",
            "avg_rent_cost": "$50 - $100/month",
            "weight": "5 - 10 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Scottish Highland Bands", "Military Bands"],
            "genres": ["Scottish Traditional", "Military"]
        },
        {
            "name": "Tuba",
            "type": "Brass",
            "price_range": "$1000 - $8000",
            "avg_rent_cost": "$80 - $200/month",
            "weight": "10 - 20 kg",
            "size": "Large",
            "hands": 1,
            "groups": ["Brass Band", "Orchestra", "Concert Band"],
            "genres": ["Classical", "Marching Band", "Jazz"]
        },
        {
            "name": "Harp",
            "type": "String",
            "price_range": "$1000 - $20000",
            "avg_rent_cost": "$100 - $300/month",
            "weight": "15 - 40 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Orchestra", "Ensembles", "Solo"],
            "genres": ["Classical", "Folk", "Pop"]
        },
        {
            "name": "Erhu",
            "type": "String",
            "price_range": "$200 - $2000",
            "avg_rent_cost": "$20 - $80/month",
            "weight": "0.5 - 1 kg",
            "size": "Small",
            "hands": 1,
            "groups": ["Chinese Orchestra", "Folk Ensembles"],
            "genres": ["Chinese Traditional", "Folk"]
        },
        {
            "name": "Didgeridoo",
            "type": "Wind",
            "price_range": "$50 - $500",
            "avg_rent_cost": "$10 - $30/month",
            "weight": "1 - 3 kg",
            "size": "Large",
            "hands": 1,
            "groups": ["Aboriginal Bands", "Folk Ensembles"],
            "genres": ["Aboriginal Traditional", "Folk"]
        },
        {
            "name": "Ocarina",
            "type": "Wind",
            "price_range": "$10 - $100",
            "avg_rent_cost": "$5 - $20/month",
            "weight": "0.1 - 0.3 kg",
            "size": "Small",
            "hands": 1,
            "groups": ["Various"],
            "genres": ["Folk", "Video Game Music"]
        },
        {
            "name": "Euphonium",
            "type": "Brass",
            "price_range": "$1000 - $5000",
            "avg_rent_cost": "$80 - $150/month",
            "weight": "5 - 10 kg",
            "size": "Large",
            "hands": 1,
            "groups": ["Brass Band", "Concert Band", "Orchestra"],
            "genres": ["Classical", "Marching Band"]
        },
        {
            "name": "Electric Keyboard",
            "type": "Keyboard",
            "price_range": "$200 - $5000",
            "avg_rent_cost": "$30 - $150/month",
            "weight": "5 - 20 kg",
            "size": "Medium",
            "hands": 1,
            "groups": ["Various"],
            "genres": ["Pop", "Rock", "Electronic"]
        },
        {
            "name": "Synthesizer",
            "type": "Keyboard",
            "price_range": "$300 - $10000",
            "avg_rent_cost": "$50 - $200/month",
            "weight": "2 - 10 kg",
            "size": "Various",
            "hands": 1,
            "groups": ["Electronic Bands", "Experimental Music Groups"],
            "genres": ["Electronic", "Ambient", "Experimental"]
        },
        {
            "name": "Harpsichord",
            "type": "Keyboard",
            "price_range": "$3000 - $30000",
            "avg_rent_cost": "$200 - $500/month",
            "weight": "50 - 100 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Baroque Ensemble", "Early Music Ensembles"],
            "genres": ["Baroque", "Classical"]
        },
        {
            "name": "Flugelhorn",
            "type": "Brass",
            "price_range": "$500 - $3000",
            "avg_rent_cost": "$50 - $150/month",
            "weight": "1 - 2 kg",
            "size": "Medium",
            "hands": 1,
            "groups": ["Jazz Band", "Brass Ensemble"],
            "genres": ["Jazz", "Classical"]
        },
        {
            "name": "Bugle",
            "type": "Brass",
            "price_range": "$100 - $500",
            "avg_rent_cost": "$20 - $50/month",
            "weight": "1 - 2 kg",
            "size": "Medium",
            "hands": 1,
            "groups": ["Military Band", "Scout Bands"],
            "genres": ["Military", "Marching Band"]
        },
        {
            "name": "Cornet",
            "type": "Brass",
            "price_range": "$300 - $2500",
            "avg_rent_cost": "$30 - $70/month",
            "weight": "2 - 3 kg",
            "size": "Medium",
            "hands": 1,
            "groups": ["Concert Band", "Brass Band"],
            "genres": ["Classical", "Marching Band", "Jazz"]
        },
        {
            "name": "Mellophone",
            "type": "Brass",
            "price_range": "$500 - $3000",
            "avg_rent_cost": "$50 - $150/month",
            "weight": "2 - 3 kg",
            "size": "Medium",
            "hands": 1,
            "groups": ["Marching Band", "Drum and Bugle Corps"],
            "genres": ["Marching Band", "Drum Corps"]
        },
        {
            "name": "Sousaphone",
            "type": "Brass",
            "price_range": "$1500 - $8000",
            "avg_rent_cost": "$100 - $250/month",
            "weight": "10 - 15 kg",
            "size": "Large",
            "hands": 1,
            "groups": ["Marching Band", "Brass Band"],
            "genres": ["Marching Band", "Brass Band"]
        },
        {
            "name": "Fiddle",
            "type": "String",
            "price_range": "$200 - $5000",
            "avg_rent_cost": "$30 - $100/month",
            "weight": "1 - 2 kg",
            "size": "Medium",
            "hands": 1,
            "groups": ["Folk Band", "Bluegrass Band"],
            "genres": ["Folk", "Bluegrass", "Country"]
        },
        {
            "name": "Maracas",
            "type": "Percussion",
            "price_range": "$10 - $50",
            "avg_rent_cost": "$5 - $20/month",
            "weight": "0.1 - 0.5 kg",
            "size": "Small",
            "hands": 2,
            "groups": ["Latin Band", "Salsa Band"],
            "genres": ["Latin", "Salsa"]
        },
        {
            "name": "Cymbals",
            "type": "Percussion",
            "price_range": "$50 - $500",
            "avg_rent_cost": "$10 - $50/month",
            "weight": "0.5 - 2 kg",
            "size": "Medium",
            "hands": 2,
            "groups": ["Orchestra", "Percussion Ensemble"],
            "genres": ["Classical", "Contemporary"]
        },
        {
            "name": "Gong",
            "type": "Percussion",
            "price_range": "$100 - $1000",
            "avg_rent_cost": "$20 - $100/month",
            "weight": "5 - 20 kg",
            "size": "Large",
            "hands": 1,
            "groups": ["Orchestra", "Percussion Ensemble"],
            "genres": ["Classical", "Asian", "Experimental"]
        },
        {
            "name": "Bells",
            "type": "Percussion",
            "price_range": "$50 - $500",
            "avg_rent_cost": "$10 - $50/month",
            "weight": "1 - 5 kg",
            "size": "Various",
            "hands": 2,
            "groups": ["Orchestra", "Handbell Choir"],
            "genres": ["Classical", "Holiday"]
        },
        {
            "name": "Tambourine",
            "type": "Percussion",
            "price_range": "$10 - $50",
            "avg_rent_cost": "$5 - $20/month",
            "weight": "0.1 - 1 kg",
            "size": "Small",
            "hands": 1,
            "groups": ["Folk Band", "Rock Band"],
            "genres": ["Folk", "Rock"]
        },
        {
            "name": "Triangle",
            "type": "Percussion",
            "price_range": "$5 - $50",
            "avg_rent_cost": "$5 - $10/month",
            "weight": "0.1 - 0.5 kg",
            "size": "Small",
            "hands": 1,
            "groups": ["Orchestra", "Percussion Ensemble"],
            "genres": ["Classical", "Folk"]
        },
        {
            "name": "Vibraphone",
            "type": "Percussion",
            "price_range": "$1000 - $10000",
            "avg_rent_cost": "$100 - $300/month",
            "weight": "50 - 100 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Jazz Band", "Percussion Ensemble"],
            "genres": ["Jazz", "Contemporary"]
        },
        {
            "name": "Xylophone",
            "type": "Percussion",
            "price_range": "$200 - $3000",
            "avg_rent_cost": "$30 - $100/month",
            "weight": "10 - 20 kg",
            "size": "Large",
            "hands": 2,
            "groups": ["Concert Band", "Percussion Ensemble"],
            "genres": ["Classical", "Contemporary"]
        },
    ]
};